# version: "3.9"
services:

  api:
    build:
      context: .
      dockerfile: ./cmd/api/Dockerfile
    environment:
      - PORT=8080
    ports:
      - "8080:8080"

  auth:
    build:
      context: .
      dockerfile: ./cmd/auth/Dockerfile
    environment:
      - PORT=8081
    ports:
      - "8081:8081"

  chat:
    build:
      context: .
      dockerfile: ./cmd/chat/Dockerfile
    environment:
      - PORT=8082
    ports:
      - "8082:8082"

volumes:
  psql_volume_bp:
